# 基于Ubuntu镜像
FROM ubuntu:20.04

# 设置时区为UTC
ENV TZ=Asia/Shanghai
RUN apt-get update && apt-get install -y tzdata

# 安装必要的依赖
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    git \
    wget \
    cmake \
    python3 \
    python3-pip \
    zlib1g-dev \
    libboost-all-dev \
    gawk \
    flex \
    bison \
    qt5-qmake \
    libprotobuf-dev \
    protobuf-compiler

# 安装Verilator
RUN git clone --branch master https://github.com/verilator/verilator.git /verilator \
    && cd /verilator && autoconf && ./configure && make -j `nproc` && sudo make install

# 安装Verilator的Python支持（可选）
RUN pip3 install verilator

# 设置工作目录
WORKDIR /workspace

# 默认命令，打开一个交互式Shell
CMD ["/bin/bash"]
